// Fill out your copyright notice in the Description page of Project Settings.


#include "TankFactory.h"
#include "Components/StaticMeshComponent.h"
#include "Components/ArrowComponent.h"
#include "Components/BoxComponent.h"
#include "HealthComponent.h"
#include "Tankogeddon.h"
#include "TankPawn.h"
#include "Kismet/GameplayStatics.h"
#include "MapLoader.h"
#include "Components/AudioComponent.h"
#include "Particles/ParticleSystemComponent.h"
#include "Serialization/Archive.h"

// Sets default values
ATankFactory::ATankFactory()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = false;

    USceneComponent* SceneComp = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
    RootComponent = SceneComp;

    BuildingMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Building Mesh"));
    BuildingMesh->SetupAttachment(SceneComp);

    TankSpawnPoint = CreateDefaultSubobject<UArrowComponent>(TEXT("Tank spawn point"));
    TankSpawnPoint->SetupAttachment(SceneComp);

    HitCollider = CreateDefaultSubobject<UBoxComponent>(TEXT("Hit collider"));
    HitCollider->SetupAttachment(SceneComp);

    HealthComponent = CreateDefaultSubobject<UHealthComponent>(TEXT("Health component"));
    HealthComponent->OnDie.AddDynamic(this, &ATankFactory::Die);
    HealthComponent->OnHealthChanged.AddDynamic(this, &ATankFactory::DamageTaked);

    SpawnEffect = CreateDefaultSubobject<UParticleSystemComponent>(TEXT("Spawn Effect"));
    SpawnEffect->SetupAttachment(SceneComp);

    SpawnAudioEffect = CreateDefaultSubobject<UAudioComponent>(TEXT("Spawn Audio Effect"));
    SpawnAudioEffect->SetupAttachment(SceneComp);

    DestroyedMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Destroyed Mesh"));
    DestroyedMesh->SetupAttachment(SceneComp);

}

void ATankFactory::TakeDamage(const FDamageData& DamageData)
{
    HealthComponent->TakeDamage(DamageData);
}

// Called when the game starts or when spawned
void ATankFactory::BeginPlay()
{
	Super::BeginPlay();

    BuildingMesh->SetVisibility(true);
    DestroyedMesh->SetVisibility(false);
    
    GetWorld()->GetTimerManager().SetTimer(SpawnTankTimerHandle, this, &ATankFactory::SpawnNewTank, SpawnTankRate, true, SpawnTankRate);

}

void ATankFactory::EndPlay(EEndPlayReason::Type EndPlayReason)
{
    Super::EndPlay(EndPlayReason);

    GetWorld()->GetTimerManager().ClearTimer(SpawnTankTimerHandle);
}

void ATankFactory::SpawnNewTank()
{
    SpawnEffect->ActivateSystem();
    SpawnAudioEffect->Play();
    FTransform SpawnTransform(TankSpawnPoint->GetComponentRotation(), TankSpawnPoint->GetComponentLocation(), FVector(1.f));
    ATankPawn* NewTank = GetWorld()->SpawnActorDeferred<ATankPawn>(SpawnTankClass, SpawnTransform, this, nullptr, ESpawnActorCollisionHandlingMethod::AlwaysSpawn);
    //
    NewTank->SetPatrollingPoints(TankWayPoints);
    //
    NewTank->FinishSpawning(SpawnTransform);
}

void ATankFactory::Die()
{
    if (MapLoader)
    {
        MapLoader->SetIsActivated(true);
    }

    UGameplayStatics::SpawnEmitterAtLocation(GetWorld(), DeathEffect, GetActorTransform());
    UGameplayStatics::PlaySoundAtLocation(GetWorld(), DeathAudioEffect, GetActorLocation());
    GetWorld()->GetTimerManager().ClearTimer(SpawnTankTimerHandle); 
    BuildingMesh->SetVisibility(false);
    DestroyedMesh->SetVisibility(true);
}

void ATankFactory::DamageTaked(float DamageValue)
{
    UE_LOG(LogTankogeddon, Log, TEXT("Factory %s taked damage:%f "), *GetName(), DamageValue);
}

